services:
  db1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: MsSql2019
    environment:
      ACCEPT_EULA: "Y"      
      MSSQL_SA_PASSWORD: "sapassword"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_ENABLE_HADR: "1"
      TZ: Asia/Manila
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
    restart: unless-stopped #NO